### PR TITLE
Update faIcons.js

### PR DESCRIPTION
**Pull request by mhimon**
Added 1500+ Icons :) 

Any issue? Contact me  https://web.facebook.com/mahbub.hasan.imon

### CODE REVIEW

**Comment by mhimon** [comment]
Credit: https://github.com/hasinhayder/vue3-icon-picker/

**Comment by tasnimAlam** [comment]
hi @mhimon , some icons are not displaying in icon picker. For example: "fas fa-caravan".

Screenshot_20210212_213355

**Comment by mhimon** [comment]
Assalamu Alaikum @tasnimAlam  Bro, Plz Update Font Awesome to the latest version.
Screenshot 2021-02-13 at 7 50 25 AM

**Comment by tasnimAlam** [comment]
Thanks

**Pull request merged**
